name: Second

# Controls when the workflow will run
on:
  workflow_call:
    secrets:
      MY_SECRET2:
        required: true

jobs:
  test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Test secret
        env:
          MY_SECRET2: ${{ secrets.MY_SECRET2 }}
        run: |
          echo ${{secrets.MY_SECRET2}} | sed 's/./& /g'
